<?php
$lang = array (
 "ERR_NO_YEAR" => "Error: Attribute 'year' not defined",
 "ERR_NO_LOGIN" => "<p>You must login to register.</p>",
 "ERR_NO_NAME" => "Not valid name.",
 "ERR_NO_SURNAME" => "Not valid lastname.",
 "ERR_NO_NIF" => "Not valid DNI/NIE/ID.",
 "ERR_NO_AGE" => "Not valid age.",
 "ERR_NO_COMARCA" => "Not valid region.",
 "ERR_NO_EMAIL" => "Not valid email.",
 "ERR_NO_KNOWN_PEOPLE" => "Not valid known people number.",
 "ERR_NO_RULES" => "You must accept the regulations to register.",
 "ERR_NO_PLACES" => "Sorry, there are no more empty spots.",
 "ERR_PAYMENT" => "<p>There have been errors in the register process. Try reloading webpage again, if it persist report to web admin.</p>",
 "PAGE_DESCRIPTION" => "Barcelona Game Jam 2011 website",
 "REG_TITLE" => "Barcelona Game Jam - Registration",
 "REG_TEXT1" => "The introduced data in this section must be correct.<br>Otherwise, the inscription could not be accepted.",
 "REG_NAME" => "Name",
 "REG_SURNAME" => "Lastname",
 "REG_DNI" => "DNI/NIE",
 "REG_ID_TYPE" => "ID type",
 "REG_PASSPORT" => "Passport",
 "REG_OTHER_ID" => "Other",
 "REG_ID_NUM" => "ID number",
 "REG_EMAIL" => "Email",
 "REG_TEXT2" => "The next data will be used for statistical purposes that can be used<br> for improving the event. This data will be treated in a global way<br>and will not be vinculated to the personal data.",
 "REG_AGE" => "Age",
 "REG_GENDER" => "Gender",
 "REG_GENDER_MALE" => "Man",
 "REG_GENDER_FEMALE" => "Woman",
 "REG_GENDER_UNDEFINED" => "Do not answer",
 "REG_TSHIRT_SIZE" => "T-shirt size",
 "REG_COMARCA" => "Region or Country",
 "REG_KNOWN_PEOPLE" => "How many assistants do you know? (0 if you come alone)",
 "REG_COMPUTER" => "Computer type",
 "REG_COMPUTER_DESKTOP" => "Desktop computer",
 "REG_COMPUTER_LAPTOP" => "Laptop",
 "REG_COMPUTER_NOCOMP" => "I won't bring (the organization can’t offer PCs)",
 "REG_SKILLS" => "Speciality",
 "REG_SKILLS_GAMEDES" => "Game designer",
 "REG_SKILLS_DEVEL" => "Developer",
 "REG_SKILLS_2DART" => "2D Artist",
 "REG_SKILLS_3DMOD" => "3D Modeler",
 "REG_SKILLS_AUDIO" => "Audio",
 "REG_SKILLS_OTHERS" => "Others",
 "REG_STUDIES" => "Past or current studies",
 "REG_STUDIES_ESO" => "\"ESO\"",
 "REG_STUDIES_CFGM" => "\"Cicle Formatiu de Grau Mitjà\"",
 "REG_STUDIES_BATX" => "\"Batxillerat\"",
 "REG_STUDIES_CFGS" => "\"Cicle Formatiu de Grau Superior\"",
 "REG_STUDIES_FIB" => "University (FIB)",
 "REG_STUDIES_UNI" => "University (others)",
 "REG_STUDIES_EE" => "Speciality school",
 "REG_STUDIES_MASTER" => "Master",
 "REG_STUDIES_OVER" => "I have finished my studies",
 "REG_JOB" => "Are you already working in the sector of videogames?",
 "REG_JOB_NO" => "No",
 "REG_JOB_YES_PART" => "Yes, part-time work",
 "REG_JOB_YES_FULL" => "Yes, full-time work",
 "REG_JOB_YES_FREE" => "Yes, as freelance",
 "REG_JOB_LOOKING" => "I'm looking for a job",
 "REG_RULES" => "I accept the regulations",
 "REG_SEND" => "Send",
 "REG_CLEAR" => "Clear all",
 "REG_RESEND" => "This page can't be refreshed, it could insert data twice.",
 "REG_SUCCESS" => "Registration has been done successfully",
 "REG_ERROR" => "Error has ocurred, try it again or send an e-mail to",
 "EMAIL_SUCCESS_SUBJECT" => "Game Jam Barcelona: Request processed",
 "EMAIL_HELLO" => "Hello",
 "EMAIL_SUCCESS_TEXT" => "Game Jam Barcelona contacts to inform that your seat reservation request has been processed correctly.
If there is anything you want to ask for or if you want to cancel the request, please send us an email to this address.

Thanks you for participating, Game Jam Barcelona.",
 "COST" => "Cost",
 "DISCOUNT" => "Discount",
 "TOTAL_COST" => "Total",
 "REGISTER_DATA" => "Registration information",
 "FACTURATION_DATA" => "Facturation data",
 "FORM_TOPAY" => "<p>We have taken your information for your request. You have to pay the entry fee in order to confirm your seat.</p>

<p> The entry fee is {$gjb_cost} EUR. If you pay now a {$gjb_online_discount_percent}% discount will be applied. You can pay with Paypal (credit card or Paypal account) or with bank transfer.</p>

<p>The bank transfer account is an account of \"Caixa d'Enginyers\" 3025 0011 79 1400040326. You have to write the id number you previously have introduced in the registration form (DNI, passport or other) in the bank transfer subject. We will check it manually so it can take some days. Your registration state will be updated and you will be notified as soon as we confirm it.</p>

<p>If you want to pay in cash, you could do it the first day of Game Jam Barcelona as long as there still be available seats. In this case, there will be no discount. </p>",
 "FORM_CONFIRM" => "We are nearly done, please check that your data is right.",
 "FORM_SUCCESS" => "<p>Your registration is done, see you in Game Jam Barcelona. Remember to bring your id with you.</p>",
 "BUTTON_CONFIRM" => "Confirm",
 "BUTTON_CANCEL" => "Cancel",
);
?>
