<?php
$lang = array (
 "ERR_NO_YEAR" => "Error: Atributo 'year' no está definido.",
 "ERR_NO_LOGIN" => "<p>Es obligatorio entrar con tu usuario para registrarse.</p>",
 "ERR_NO_NAME" => "No se ha introducido un nombre correcto.",
 "ERR_NO_SURNAME" => "No se han introducido los apellidos correctamente.",
 "ERR_NO_NIF" => "El DNI/NIE/ID introducido no es correcto.",
 "ERR_NO_AGE" => "La edad introducida no es correcta.",
 "ERR_NO_COMARCA" => "No se ha introducido una comarca correcta.",
 "ERR_NO_EMAIL" => "El correo electrónico introducido no es valido.",
 "ERR_NO_KNOWN_PEOPLE" => "El número de asistentes no es valido.",
 "ERR_NO_RULES" => "Se debe aceptar la normativa para poder registrarse.",
 "ERR_PAYMENT" => "<p>Se ha producido un error en el proceso de pago. Prueba cargando la página de nuevo y si continua contacta con el administrador del sitio web.</p>",
 "PAGE_DESCRIPTION" => "Sitio web de la Game Jam Barcelona 2011",
 "REG_TITLE" => " Game Jam Barcelona - Inscripción",
 "REG_TEXT1" => "Los datos personales de este apartado tienen que ser correctos, en caso <br> contrario, se podrá dar por no válida la inscripción.",
"REG_NAME" => "Nombre",
"REG_SURNAME" => "Apellidos",
"REG_DNI" => "DNI/NIE",
"REG_ID_TYPE" => "Tipo documento",
"REG_PASSPORT" => "Pasaporte",
"REG_OTHER_ID" => "Otros",
"REG_ID_NUM" => "Número documento",
"REG_EMAIL" => "Email",
"REG_TEXT2" => "Los siguientes datos se utilizarán para hacer estudios, los cuales servirán<br> para mejorar el evento. Estos datos se tratarán de forma global <br>y sin vincularlos a los datos personales.",
"REG_AGE" => "Edad",
"REG_GENDER" => "Sexo",
"REG_GENDER_MALE" => "Hombre",
"REG_GENDER_FEMALE" => "Mujer",
"REG_COMARCA" => "Comarca o Provincia",
"REG_KNOWN_PEOPLE" => "¿A cuántos asistentes conoces? (0 si vienes solo)",
"REG_COMPUTER" => "Tipo de ordenador",
"REG_COMPUTER_DESKTOP" => "Sobremesa",
"REG_COMPUTER_LAPTOP" => "Portátil",
"REG_COMPUTER_NOCOMP" => "No llevo (La organización no puede ofrecer PCs)",
"REG_SKILLS" => "Especialidad",
"REG_SKILLS_GAMEDES" => "Diseño del Juego",
"REG_SKILLS_DEVEL" => "Programación",
"REG_SKILLS_2DART" => "Imágenes 2D",
"REG_SKILLS_3DMOD" => "Modelos 3D",
"REG_SKILLS_AUDIO" => "Sonido",
"REG_SKILLS_OTHERS" => "Otros",
"REG_STUDIES" => "Últimos o actuales estudios",
"REG_STUDIES_ESO" => "ESO",
"REG_STUDIES_CFGM" => "Ciclo Formativo de Grado Medio",
"REG_STUDIES_BATX" => "Bachillerato",
"REG_STUDIES_CFGS" => "Ciclo Formativo de Grado Superior",
"REG_STUDIES_FIB" => "Universidad, en la FIB",
"REG_STUDIES_UNI" => "Universidad otros",
"REG_STUDIES_EE" => "Escuela especializada",
"REG_STUDIES_MASTER" => "Máster",
"REG_STUDIES_OVER" => "He acabado de estudiar",
"REG_JOB" => "¿Trabajas en el sector?",
"REG_JOB_NO" => "No",
"REG_JOB_YES_PART" => "Sí, jornada parcial",
"REG_JOB_YES_FULL" => "Sí, jornada completa",
"REG_JOB_YES_FREE" => "Sí, trabajos puntuales",
"REG_JOB_LOOKING" => "Actualmente busco (quizás otro) trabajo",
"REG_RULES" => "Acepto la normativa",
"REG_SEND" => "Enviar",
"REG_CLEAR" => "Borrar",
"REG_RESEND" => "Esta página no se puede actualizar, se insertarían datos duplicados.",
"REG_SUCCESS" => "Inscripción realitzada con éxito",
"REG_ERROR" => "Se ha producido un error, vuelve a intentarlo o envia un e-mail a",
"EMAIL_SUCCESS_SUBJECT" => "Game Jam Barcelona: Solicitud procesada",
"EMAIL_HELLO" => "Hola",
"EMAIL_SUCCESS_TEXT" => "Game Jam Barcelona se pone en contacto para comunicarte que tu solicitud de inscripción ha sido procesada correctamente.
Si hay cualquier duda o si quieres dar de baja la solicitud, agradecemos que envíes­ un correo a esta misma dirección.

Gracias por todo, atentamente
La organización de la Game Jam Barcelona.",
"COST" => "Precio",
"DISCOUNT" => "Descuento",
"TOTAL_COST" => "Total",
"REGISTER_DATA" => "Datos de inscripción",
"FACTURATION_DATA" => "Datos de facturación",
"FORM_TOPAY" => "<p>Ya se han tomado los datos para poder solicitar tu inscripción. Para confirmar tu plaza has de realizar el pago que se indica a continuación.</p>

<p>El precio de la inscripción es de {$gjb_cost} EUR. El pago anticipado tiene un descuento de {$gjb_online_discount_percent}%. Los métodos de pago anticipado son Paypal (con tarjeta de crédito o cuenta Paypal) o por transferencia bancaria.</p>

<p>Para realizar el pago por transferencia bancaria se deberá hacer un ingreso del precio total indicado abajo a la cuenta de Caixa d'Enginyers 3025 0011 79 1400040326 y <b>poner como concepto del pago el DNI/NIE que se ha introducido al formulario de inscripción</b>. La comprobación es manual, puede tardar unos pocos dias. Una vez confirmado el pago se actualizará tu estado de inscripción y serás notificado.</p>

<p>En el caso de querer hacer el pago en efectivo se podrá hacer en la misma Game Jam Barcelona efectuando una compra no anticipada y siempre y cuando haya plazas disponibles.</p>",
"FORM_CONFIRM" => "Ya falta poco, comprueba que todos los datos sean correctos.",
"FORM_SUCCESS" => "<p>Tu plaza está confirmada, nos vemos en la Game Jam Barcelona. Recuerda traer tu DNI o documento de identificación correspondiente.</p>",
"BUTTON_CONFIRM" => "Confirmar",
"BUTTON_CANCEL" => "Cancelar",
);
?>
