<?php
$lang = array (
 "ERR_NO_YEAR" => "Error: Atribut 'year' no està definit.",
 "ERR_NO_LOGIN" => "<p>És obligatori entrar amb el teu usari per registrar-te.</p>",
 "ERR_NO_NAME" => "No s'ha introduit el nom correctament.",
 "ERR_NO_SURNAME" => "No s'han introduït els cognoms correctament.",
 "ERR_NO_NIF" => "El DNI/NIE/ID introduït no és correcte.",
 "ERR_NO_AGE" => "La edat introduïda no és correcte.",
 "ERR_NO_COMARCA" => "No s'ha introduït la comarca correctament.",
 "ERR_NO_EMAIL" => "El correu electrònic introduït no és vàlid.",
 "ERR_NO_KNOWN_PEOPLE" => "El número d'assistents no és vàlid.",
 "ERR_NO_RULES" => "S'ha d'acceptar la normativa per registrar-se.",
 "ERR_PAYMENT" => "<p>S'ha produït un error en el procés de pagament. Prova de carregar la pàgina de nou i si continua contacta amb l'administrador del lloc web.</p>",
 "PAGE_DESCRIPTION" => "Lloc web de la Game Jam Barcelona 2011",
 "REG_TITLE" => "Game Jam Barcelona - Inscripció",
 "REG_TEXT1" => "Les dades personals d'aquest apartat han de ser correctes, en cas <br> contrari, es podrà donar per no vàlida l'inscripció.",
 "REG_NAME" => "Nom",
 "REG_SURNAME" => "Cognoms",
 "REG_DNI" => "DNI/NIE",
 "REG_ID_TYPE" => "Tipus document",
 "REG_PASSPORT" => "Passaport",
 "REG_OTHER_ID" => "Altres",
 "REG_ID_NUM" => "Número document",
 "REG_EMAIL" => "Email",
 "REG_TEXT2" => "Les següents dades s'utilitzaran per a fer estudis, els quals serviran per <br>tal de millorar l'esdeveniment. Aquestes dades es tractaran de forma global <br>i sense vincular-les a les dades personals.",
 "REG_AGE" => "Edat",
 "REG_GENDER" => "Sexe",
 "REG_GENDER_MALE" => "Home",
 "REG_GENDER_FEMALE" => "Dona",
 "REG_COMARCA" => "Comarca",
 "REG_KNOWN_PEOPLE" => "A quants assistents coneixes? (0 si véns sol)",
 "REG_COMPUTER" => "Tipus d'ordinador",
 "REG_COMPUTER_DESKTOP" => "Sobretaula",
 "REG_COMPUTER_LAPTOP" => "Portàtil",
 "REG_COMPUTER_NOCOMP" => "No porto (L'organització no pot oferir PCs)",
 "REG_SKILLS" => "Especialitat",
 "REG_SKILLS_GAMEDES" => "Disseny del Joc",
 "REG_SKILLS_DEVEL" => "Programació",
 "REG_SKILLS_2DART" => "Imatges 2D",
 "REG_SKILLS_3DMOD" => "Models 3D",
 "REG_SKILLS_AUDIO" => "So",
 "REG_SKILLS_OTHERS" => "Altres",
 "REG_STUDIES" => "Últims o actuals estudis",
 "REG_STUDIES_ESO" => "ESO",
 "REG_STUDIES_CFGM" => "Cicle Formatiu de Grau Mitjà",
 "REG_STUDIES_BATX" => "Batxillerat",
 "REG_STUDIES_CFGS" => "Cicle Formatiu de Grau Superior",
 "REG_STUDIES_FIB" => "Universitat, a la FIB",
 "REG_STUDIES_UNI" => "Universitat altres",
 "REG_STUDIES_EE" => "Escola especialitzada",
 "REG_STUDIES_MASTER" => "Màster",
 "REG_STUDIES_OVER" => "He acabat d'estudiar",
 "REG_JOB" => "Treballes al sector?",
 "REG_JOB_NO" => "No",
 "REG_JOB_YES_PART" => "Sí, a temps parcial",
 "REG_JOB_YES_FULL" => "Sí, a temps complet",
 "REG_JOB_YES_FREE" => "Sí, treballs puntuals",
 "REG_JOB_LOOKING" => "Actualment busco (potser una altra) feina",
 "REG_RULES" => "Accepto la normativa",
 "REG_SEND" => "Enviar",
 "REG_CLEAR" => "Esborrar",
 "REG_RESEND" => "Aquesta pàgina no es pot actualizar, s'insertarien dades duplicades.",
 "REG_SUCCESS" => "Inscripció realitzada amb èxit",
 "REG_ERROR" => "S'ha produït un error, torna a intentar-ho o envia un e-mail a",
 "EMAIL_SUCCESS_SUBJECT" => "Game Jam Barcelona: Sol·licitud processada",
 "EMAIL_HELLO" => "Hola",
 "EMAIL_SUCCESS_TEXT" => "Game Jam Barcelona es posa en contacte amb tu per comunicar-te que la teva sol·licitud de reserva de plaça ha estat processada correctament.
Si hi ha qualsevol dubte o si vols donar de baixa la sol·licitud, agraïm que enviïs un correu a aquesta mateixa adreça.

Gràcies per tot, atentament
La organització de la Game Jam Barcelona",
 "COST" => "Preu",
 "DISCOUNT" => "Descompte",
 "TOTAL_COST" => "Total",
 "REGISTER_DATA" => "Dades d’inscripció",
 "FACTURATION_DATA" => "Dades de facturació",
 "FORM_TOPAY" => "<p>Ja s'han pres les dades per a poder sol·licitar la teva inscripció. Per a confirmar la teva plaça has de realitzar el pagament que s'indica a continuació.</p>

 <p>El preu de la inscripció és de {$gjb_cost} EUR. El pagament anticipat té un descompte del {$gjb_online_discount_percent}%. Els mètodes de pagament anticipat són Paypal (amb targeta de crèdit o compte Paypal) o per transferència bancaria.</p>

 <p>Per realitzar el pagament per transferència bancaria s'haurà de fer un ingrés del preu total indicat abaix al compte de Caixa d'Enginyers 3025 0011 79 1400040326 i <b>posar com a concepte del pagament el DNI/NIE que heu introduït al formulari d'inscripció</b>. La comprovació es manual, pot trigar uns pocs dies. Un cop confirmat el pagament s'actualitzarà el teu estat d'inscripció i seràs notificat.</p>

 <p>En el cas de voler fer el pagament en efectiu es podrà fer en la mateixa Game Jam Barcelona efectuant una compra no anticipada i sempre que hi hagi places disponibles.</p>",
 "FORM_CONFIRM" => "Ja falta poc, comprova que totes les dades siguin correctes.",
 "FORM_SUCCESS" => "<p>La teva plaça està confirmada, ens veiem a la Game Jam Barcelona. Recorda dur el teu DNI o document d'identificació corresponent.</p>",
 "BUTTON_CONFIRM" => "Confirmar",
 "BUTTON_CANCEL" => "Cancel·lar",
);
?>
